### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by b-smiley** [b-smiley/read-back-app#17]
- [ ] Text to speech on evidence
- [ ] Court Proceeding (10s timer)
- [ ] Buffer on the transcript (see Sachin's code)
- [ ] hard code evidence image/data
- [ ] styling
- [ ] remaining figma
